### ISSUE TITLE
How can I set the original language?

### ISSUE THREAD

**Issue by iec989** [JoggApp/laravel-google-translate#32]
Re: #31 which was closed

How can I set the original language if I don't want Google to autodetect?

I might be translating a short phrase from Google from Spanish into English, but however Google might think it's Portuguese due to the amount of false friends that we have. How can I tell the API to translate it from Spanish?

**Comment by introwit** [comment]
@iec989 this package does not support that yet, also we don't know if google's sdk does it either. If it does, feel free to PR the feature to this package.

**Comment by ascanipek** [comment]
> Re: #31 which was closed
> 
> How can I set the original language if I don't want Google to autodetect?
> 
> I might be translating a short phrase from Google from Spanish into English, but however Google might think it's Portuguese due to the amount of false friends that we have. How can I tell the API to translate it from Spanish?

I couldn't use this repo because of the same need. But I found the solution in the original google repo: [google-cloud-php-translate](https://github.com/googleapis/google-cloud-php-translate).

Here you can specify the source language parameter:

$translate->translate('Hello World!', ['source' => 'en', 'target' => 'tr');
